Cassandra Computed Tiles release
CatalystCode/project-fortis-spark pull request #85
Opened 2017-08-12 04:00 UTC by erikschlegel

This release is responsible for populating the following cassandra table through Dataframes and Spark SQL

```CREATE TABLE computedtiles (
    periodstartdate timestamp,
    periodenddate timestamp,
    periodtype text,
    pipelinekey text,
    period text,
    tilez int,
    tilex int,
    tiley int,
    externalsourceid text,
    mentioncount bigint,
    avgsentimentnumerator bigint,
    heatmap text,
    conjunctiontopic1 text,
    conjunctiontopic2 text,
    conjunctiontopic3 text,
    PRIMARY KEY ((periodtype, conjunctiontopic1, conjunctiontopic2, conjunctiontopic3, tilez, period), tilex, tiley, periodstartdate, periodenddate, pipelinekey, externalsourceid)
);```

2017-08-12 04:10 UTC, kevinhartman commented on project/plugins.sbt
> -addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.3")
What's the reason for removing these? Without `sbt-assembly`, we cannot build the project. It may be dependent on some of the above plugins as well.

2017-08-12 05:11 UTC, kevinhartman requested changes
Looks like some accidental project file edits made it in here. Please revert those before merging :)

2017-08-12 05:11 UTC, kevinhartman commented on .gitignore
> +project/*
Project directory should **NOT** be excluded.

2017-08-12 05:11 UTC, kevinhartman commented on .gitignore
> +out/*
What are the above 2 exclusions guarding against? We haven't had a problem with these in the past. Can we revert this file?

2017-08-12 05:11 UTC, kevinhartman commented on out/production/project-fortis-spark/main/resources/ApplicationInsights.xml
> +<?xml version="1.0" encoding="utf-8"?>
We're using environment variables to configure app insights, so we shouldn't need this file.

2017-08-12 05:11 UTC, kevinhartman commented on .gitignore
> +out/*
**EDIT**: 
I see the project folder was accidentally excluded. Plz fix :)

2017-08-12 05:11 UTC, kevinhartman commented on src/main/scala/com/microsoft/partnercatalyst/fortis/spark/sinks/cassandra/udfs/FortisUdfFunctions.scala
>      Option(number) match {
In the general case, we should not define a usage contract of a method such that a `Double` parameter is expected to be sometimes `null`. Aside, this method seems very specific (a default of 1 when it's called in such a way)—maybe it shouldn't be at this scope? Aside, shouldn't `defaultValue` just be a `Double` that's default value is 1?

2017-08-12 05:11 UTC, kevinhartman commented on src/main/scala/com/microsoft/partnercatalyst/fortis/spark/sinks/cassandra/udfs/FortisUdfFunctions.scala
> +      case hm => hm.get.mentioncountagg
```scala
case Some(hm) => hm.mentioncountagg
```

Same fix needed above.

2017-08-12 05:39 UTC, erikschlegel commented on project/plugins.sbt
> -addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.3")
dealing with some issues with my build and didnt realize these were removed until looking at the PR. Hold off on reviewing until I circle back.

2017-08-14 14:56 UTC, Smarker commented on src/main/scala/com/microsoft/partnercatalyst/fortis/spark/sinks/cassandra/aggregators/ComputedTilesAggregator.scala
> +  private val DetilaTileIdColumnName = "detailtileid"
spelling: DetailTileIdColumnName

2017-08-14 15:34 UTC, kevinhartman approved these changes
LGTM, with the caveat that someone who's more familiar with the computed tiles schema & approach should also review (perhaps @jcjimenez).

2017-08-14 15:34 UTC, kevinhartman commented on src/main/scala/com/microsoft/partnercatalyst/fortis/spark/sinks/cassandra/aggregators/ComputedTilesAggregator.scala
> +      display match {
```scala
if (display) column else s"'all' as ${column}"
```

2017-08-14 15:34 UTC, kevinhartman commented on src/main/scala/com/microsoft/partnercatalyst/fortis/spark/sinks/cassandra/aggregators/ComputedTilesAggregator.scala
> +      val computedTilesSourceDF = session.sqlContext.read.format(CassandraFormat)
nit: wrong indent.

2017-08-14 15:34 UTC, kevinhartman commented on src/main/scala/com/microsoft/partnercatalyst/fortis/spark/sinks/cassandra/aggregators/FortisAggregator.scala
> + override def DfTableNameFlattenedEvents: String = s"$DataFrameNameFlattenedEvents$FortisTargetTablename"
nite: wrong indent

2017-08-14 15:34 UTC, kevinhartman commented on src/main/scala/com/microsoft/partnercatalyst/fortis/spark/sinks/cassandra/dto/FortisRecords.scala
> +                         override val periodstartdate: Long,
nit: wrong indent

2017-08-14 17:56 UTC, merged